"""Mapeamento de valores legados para o processo comercial oficial."""

LEGACY_STAGE_MAP = {
    "Primeiro Contato": "Contato",
    "Contato inicial": "Contato",
    "Primeiro contato": "Contato",
    "Prospectando": "Qualificação",
    "Prospecção": "Qualificação",
    "Apresentação": "Reunião",
    "Proposta Enviada": "Proposta",
    "Proposta enviada": "Proposta",
    "Aguardando resposta": "Retorno",
    "Follow-up": "Retorno",
    "Follow up": "Retorno",
    "Sem resposta": "Retorno",
    "Fechamento": "Negociação",
    "Ganho": "Fechado",
    "Perdido": "Negociação",
    "Chamado Whats": "Contato",
    "Conversando": "Qualificação",
    "Retornar": "Retorno",
    "Ligação retornar": "Retorno",
    "Sem Resposta": "Retorno",
    "Não responde": "Retorno",
    "Ligação": "Contato",
    "Ligação - Conversando Whats": "Contato",
}

LEGACY_RESULT_MAP = {
    "Sem resposta": "Cliente não respondeu",
    "Não respondeu": "Cliente não respondeu",
    "Contato realizado": "Cliente respondeu",
    "Tem interesse": "Cliente respondeu",
    "Interesse confirmado": "Cliente respondeu",
    "Interesse não confirmado": "Cliente não respondeu",
    "Reunião marcada": "Avançou de etapa",
    "Reunião confirmada": "Avançou de etapa",
    "Reunião agendada": "Avançou de etapa",
    "Reunião realizada": "Avançou de etapa",
    "Reunião não realizada": "Cliente não respondeu",
    "Lead qualificado": "Avançou de etapa",
    "Lead não qualificado": "Sem interesse",
    "Proposta solicitada": "Avançou de etapa",
    "Orçamento enviado": "Avançou de etapa",
    "Proposta enviada": "Avançou de etapa",
    "Ajuste solicitado": "Avançou de etapa",
    "Follow-up realizado": "Pediu retorno",
    "Em análise pelo cliente": "Pediu retorno",
    "Em negociação": "Avançou de etapa",
    "Fechado": "Avançou de etapa",
    "Venda fechada": "Avançou de etapa",
    "Não tem interesse": "Sem interesse",
    "Lead encerrado": "Sem interesse",
    "Encerrar oportunidade": "Sem interesse",
    "Número incorreto": "Contato inválido",
    "Sem WhatsApp": "Contato inválido",
    "Outro": "",
}

LEGACY_ACTION_MAP = {
    "Primeiro contato": "Fazer primeiro contato",
    "Fazer follow-up": "Fazer acompanhamento da proposta",
    "Follow-up": "Fazer acompanhamento da proposta",
    "Realizar follow-up da proposta": "Fazer acompanhamento da proposta",
    "Ligar agora": "Retornar contato",
    "Retorno": "Retornar contato",
    "Agendar": "Agendar reunião",
    "Agendar retorno": "Reagendar retorno",
    "Enviar orçamento": "Enviar proposta",
    "Cobrar proposta": "Fazer acompanhamento da proposta",
    "Retomar qualificação": "Qualificar lead",
    "Retomar negociação": "Negociar condições",
    "Definir próxima ação": "Qualificar lead",
    "Encerrar oportunidade": "Confirmar fechamento",
}

LEGACY_NEXT_ACTION_MAP = {
    "Fazer primeiro contato": "Fazer primeiro contato",
    "Verificar dados do lead": "Fazer primeiro contato",
    "Atribuir responsável": "Fazer primeiro contato",
    "Realizar contato": "Fazer primeiro contato",
    "Enviar apresentação inicial": "Fazer primeiro contato",
    "Confirmar interesse": "Qualificar lead",
    "Qualificar lead": "Qualificar lead",
    "Entender necessidade": "Qualificar lead",
    "Identificar decisor": "Qualificar lead",
    "Validar orçamento": "Qualificar lead",
    "Definir próximo passo": "Qualificar lead",
    "Agendar reunião": "Agendar reunião",
    "Confirmar reunião": "Agendar reunião",
    "Realizar reunião": "Agendar reunião",
    "Reagendar reunião": "Agendar reunião",
    "Criar proposta": "Criar proposta",
    "Revisar proposta": "Criar proposta",
    "Enviar proposta": "Criar proposta",
    "Ajustar proposta": "Criar proposta",
    "Retornar contato": "Retornar contato",
    "Fazer acompanhamento da proposta": "Retornar contato",
    "Verificar decisão": "Retornar contato",
    "Cobrar posicionamento": "Retornar contato",
    "Reagendar retorno": "Retornar contato",
    "Negociar condições": "Negociar condições",
    "Ajustar valores": "Negociar condições",
    "Ajustar escopo": "Negociar condições",
    "Definir forma de pagamento": "Negociar condições",
    "Enviar contrato": "Negociar condições",
    "Confirmar assinatura": "Confirmar fechamento",
    "Confirmar pagamento": "Confirmar fechamento",
    "Confirmar fechamento": "Confirmar fechamento",
    "Iniciar implantação": "Confirmar fechamento",
    "Encerrar processo comercial": "Confirmar fechamento",
    "Primeiro contato": "Fazer primeiro contato",
    "Fazer follow-up": "Retornar contato",
    "Follow-up": "Retornar contato",
    "Realizar follow-up da proposta": "Retornar contato",
    "Ligar agora": "Retornar contato",
    "Retorno": "Retornar contato",
    "Agendar": "Agendar reunião",
    "Agendar retorno": "Retornar contato",
    "Enviar orçamento": "Criar proposta",
    "Cobrar proposta": "Retornar contato",
    "Retomar qualificação": "Qualificar lead",
    "Retomar negociação": "Negociar condições",
    "Definir próxima ação": "Qualificar lead",
    "Encerrar oportunidade": "Confirmar fechamento",
}

LEGACY_CHANNEL_MAP = {
    "Whats": "WhatsApp",
    "Whatsapp": "WhatsApp",
    "whatsapp": "WhatsApp",
    "Telefone": "Ligação",
    "ligacao": "Ligação",
    "Email": "E-mail",
    "email": "E-mail",
    "Meet": "Reunião online",
    "reuniao": "Reunião online",
    "Tarefa": "Mensagem interna",
    "tarefa": "Mensagem interna",
    "Follow-up": "WhatsApp",
}

LEGACY_STATUS_MAP = {
    "Concluida": "Concluída",
    "concluida": "Concluída",
    "Pendente": "Pendente",
    "pendente": "Pendente",
    "Atrasada": "Atrasada",
    "atrasada": "Atrasada",
    "Cancelada": "Cancelada",
    "cancelada": "Cancelada",
}

LEGACY_OPPORTUNITY_STATUS_MAP = {
    "Aberto": "Aberta",
    "Perdido": "Fechada perdida",
    "Ganho": "Fechada ganha",
    "Encerrado": "Encerrada",
}

MIGRATION_FIELD_LABELS = {
    "stage": "Etapa",
    "stage_override": "Etapa (override)",
    "process_action": "Atividade",
    "title": "Atividade (título)",
    "next_action": "Próxima ação",
    "next_action_description": "Próxima ação (descrição)",
    "result": "Resultado",
    "channel": "Canal",
    "next_action_channel": "Canal da próxima ação",
    "status": "Status",
    "opportunity_status": "Status da oportunidade",
}
